## Dataset: https://www.kaggle.com/datasets/goyaladi/twitter-dataset

In [52]:
import pandas as pd

In [55]:
data_path = "/content/twitter_dataset.csv"

In [56]:
df = pd.read_csv(data_path)

In [57]:
df.shape

(10000, 6)

In [58]:
df.head()

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,Party least receive say or single. Prevent pre...,2,25,30-01-2023 11:00
1,2,richardhester,Hotel still Congress may member staff. Media d...,35,29,02-01-2023 22:45
2,3,williamsjoseph,Nice be her debate industry that year. Film wh...,51,25,18-01-2023 11:25
3,4,danielsmary,Laugh explain situation career occur serious. ...,37,18,10-04-2023 22:06
4,5,carlwarren,Involve sense former often approach government...,27,80,24-01-2023 07:12

## Lowercase

In [61]:
df["Text"][0]

'Party least receive say or single. Prevent prevent husband affect. May himself cup style evening protect. Effect another themselves stage perform.<br>\nPossible try tax share style television with. Successful much sell development economy effect.'

In [62]:
df["Text"] = df["Text"].str.lower()

In [63]:
df

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,party least receive say or single. prevent pre...,2,25,30-01-2023 11:00
1,2,richardhester,hotel still congress may member staff. media d...,35,29,02-01-2023 22:45
2,3,williamsjoseph,nice be her debate industry that year. film wh...,51,25,18-01-2023 11:25
3,4,danielsmary,laugh explain situation career occur serious. ...,37,18,10-04-2023 22:06
4,5,carlwarren,involve sense former often approach government...,27,80,24-01-2023 07:12
...,...,...,...,...,...,...
9995,9996,ntate,agree reflect military box ability ever hold. ...,81,86,15-01-2023 11:46
9996,9997,garrisonjoshua,born which push still. degree sometimes contro...,73,100,06-05-2023 00:46
9997,9998,adriennejackson,you day agent likely region. teacher data mess...,10,62,27-02-2023 14:55
9998,9999,kcarlson,guess without successful save. particular natu...,21,60,09-01-2023 16:09
9999,10000,vdickerson,body onto understand team about product beauti...,65,54,19-04-2023 01:35

In [65]:
df["Text"][0]

'party least receive say or single. prevent prevent husband affect. may himself cup style evening protect. effect another themselves stage perform.<br>\npossible try tax share style television with. successful much sell development economy effect.'

## Remove HTML Tags

In [66]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [67]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [68]:
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [69]:
df["Text"] = df["Text"].apply(remove_html_tags)

In [70]:
df["Text"][0]

'party least receive say or single. prevent prevent husband affect. may himself cup style evening protect. effect another themselves stage perform.\npossible try tax share style television with. successful much sell development economy effect.'

## Remove URL

In [71]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [72]:

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)
text1 = 'Check out my youtube https://www.youtube.com/dswithbappy dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com/'

In [73]:
remove_url(text2)

'Check out my linkedin '

## Punctuation Handling

In [74]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [75]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [76]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [77]:
text = 'string. With. Punctuation?'

In [78]:
start = time.time()
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
9.000301361083984

In [79]:
def remove_punc1(text):
    return text.translate(str.maketrans('', '', exclude))

In [80]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

7.212162017822266

In [81]:
time1/time2

1.2479338842975207

In [84]:
df['Text'][0]

'party least receive say or single. prevent prevent husband affect. may himself cup style evening protect. effect another themselves stage perform.\npossible try tax share style television with. successful much sell development economy effect.'

In [85]:
remove_punc1(df["Text"][0])

'party least receive say or single prevent prevent husband affect may himself cup style evening protect effect another themselves stage perform\npossible try tax share style television with successful much sell development economy effect'

## Chat Conversion Handle

In [87]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible'
}


{
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

{'FYI': 'For Your Information',
 'ASAP': 'As Soon As Possible',
 'BRB': 'Be Right Back',
 'BTW': 'By The Way',
 'OMG': 'Oh My God',
 'IMO': 'In My Opinion',
 'LOL': 'Laugh Out Loud',
 'TTYL': 'Talk To You Later',
 'GTG': 'Got To Go',
 'TTYT': 'Talk To You Tomorrow',
 'IDK': "I Don't Know",
 'TMI': 'Too Much Information',
 'IMHO': 'In My Humble Opinion',
 'ICYMI': 'In Case You Missed It',
 'AFAIK': 'As Far As I Know',
 'FAQ': 'Frequently Asked Questions',
 'TGIF': "Thank God It's Friday",
 'FYA': 'For Your Action'}

In [88]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [89]:
chat_conversion('Do this work ASAP')

'Do this work As Soon As Possible'

## Incorrect Text Handling

In [90]:
from textblob import TextBlob

In [91]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

## Stopwords

In [92]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [93]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [94]:
len(stopwords.words('english'))

198

In [95]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [96]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [97]:
df.head()

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,party least receive say or single. prevent pre...,2,25,30-01-2023 11:00
1,2,richardhester,hotel still congress may member staff. media d...,35,29,02-01-2023 22:45
2,3,williamsjoseph,nice be her debate industry that year. film wh...,51,25,18-01-2023 11:25
3,4,danielsmary,laugh explain situation career occur serious. ...,37,18,10-04-2023 22:06
4,5,carlwarren,involve sense former often approach government...,27,80,24-01-2023 07:12

In [99]:
df['Text'].apply(remove_stopwords)

0       party least receive say  single. prevent preve...
1       hotel still congress may member staff. media d...
2       nice   debate industry  year. film  generation...
3       laugh explain situation career occur serious. ...
4       involve sense former often approach government...
                              ...
9995    agree reflect military box ability ever hold. ...
9996    born  push still. degree sometimes control spa...
9997     day agent likely region. teacher data message...
9998    guess without successful save. particular natu...
9999    body onto understand team  product beautiful. ...
Name: Text, Length: 10000, dtype: object

## Remove Emoji Handle

In [100]:

import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [101]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [102]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [103]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 15.6 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [104]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [105]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

## Tokenization

### 1. Using the split function

In [106]:
# word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [107]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [108]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [109]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

### 2. Regular Expression

In [110]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_6599/3190589682.py:3: SyntaxWarning: invalid escape sequence '\w'
  tokens = re.findall("[\w']+", sent3)

['I', 'am', 'going', 'to', 'delhi']

In [111]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

### 3.NLTK (Natural Language Toolkit)

In [114]:
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [115]:
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [116]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [117]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [118]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [119]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

### 4. Spacy

In [120]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [121]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [122]:
doc4 = nlp(sent1)
doc4

I am going to visit delhi!

In [124]:
for token in doc4:
    print(token)

I
am
going
to
visit
delhi
!

In [125]:
df.head()

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,party least receive say or single. prevent pre...,2,25,30-01-2023 11:00
1,2,richardhester,hotel still congress may member staff. media d...,35,29,02-01-2023 22:45
2,3,williamsjoseph,nice be her debate industry that year. film wh...,51,25,18-01-2023 11:25
3,4,danielsmary,laugh explain situation career occur serious. ...,37,18,10-04-2023 22:06
4,5,carlwarren,involve sense former often approach government...,27,80,24-01-2023 07:12

## Stemmer

In [126]:
from nltk.stem.porter import PorterStemmer

In [127]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [128]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [129]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [130]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

## Lemmatization

### NOTE: Stemming & lamatization are same to retrieve root words but lamatization is worked good. Lamatization is slow & stemming is fast

In [131]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun